# 2.1. Data Manipulation
* Numpy: CPU well-supported
* Tensor: GPU well-supported; auto differentiation supported.

In [1]:
import torch

## 2.1.1. Getting started

### Tensor(vector/matrix)

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.numel() #total number of elements

12

In [4]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Automatically calculate the width or height(fill in "-1")

In [5]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Initialize zeros/ones

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.randn((3,4)) # sample from a normal distribution(mean:0, std:1)

tensor([[ 0.5939,  0.4182,  0.0657,  0.0186],
        [-0.8385, -1.5204,  2.7166,  0.0348],
        [ 0.3862, -0.5307, -1.5248,  0.9714]])

### Create Tensor by a list or nest list

In [10]:
lst = [[1,2,3], [4,5,6], [7,8,9]]
torch.tensor(lst)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 2.1.2 Operations

In [11]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
torch.exp(y) #exponentiation e^2

tensor([7.3891, 7.3891, 7.3891, 7.3891])

### Concatenate tensors by row/column

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [21., 22., 23., 24.],
         [25., 26., 27., 28.],
         [29., 30., 31., 32.]]),
 tensor([[ 0.,  1.,  2.,  3., 21., 22., 23., 24.],
         [ 4.,  5.,  6.,  7., 25., 26., 27., 28.],
         [ 8.,  9., 10., 11., 29., 30., 31., 32.]]))

### logical statements

In [17]:
X == Y, Y > X

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [18]:
X.sum()

tensor(66.)