# 2.1. Data Manipulation
* Numpy: CPU well-supported
* Tensor: GPU well-supported; auto differentiation supported.

In [1]:
import torch

## 2.1.1. Getting started

### Tensor(vector/matrix)

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel() # total number of elements

12

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Automatically calculate the width or height(fill in "-1")

In [6]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Initialize zeros/ones

In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn((3,4)) # sample from a normal distribution(mean:0, std:1)

tensor([[-0.3601, -0.3246, -0.3154,  0.9647],
        [ 0.9820, -2.6622,  1.4354, -0.9026],
        [ 1.0870,  0.4497, -0.3765,  1.1478]])

### Create Tensor by a list or nest list

In [11]:
lst = [[1,2,3], [4,5,6], [7,8,9]]
torch.tensor(lst)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 2.1.2 Operations

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(y) #exponentiation e^2

tensor([7.3891, 7.3891, 7.3891, 7.3891])

### Concatenate tensors by row/column

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]]))

In [15]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [21., 22., 23., 24.],
         [25., 26., 27., 28.],
         [29., 30., 31., 32.]]),
 tensor([[ 0.,  1.,  2.,  3., 21., 22., 23., 24.],
         [ 4.,  5.,  6.,  7., 25., 26., 27., 28.],
         [ 8.,  9., 10., 11., 29., 30., 31., 32.]]))

### logical statements

In [16]:
X == Y, Y > X

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [17]:
X.sum()

tensor(66.)

## 2.1.3 Broadcasting Mechanism
> Operations on tensors with different shape

In [20]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
# Expand Tensor to the same shape, then do the calculations
a, b, a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

## 2.1.4. Indexing and Slicing

In [22]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[0], X[-1], X[1:3] # slicing by row

(tensor([0., 1., 2., 3.]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([0., 4., 8.]))

In [28]:
X[:, 0], X[:, ::2] # slicing by column

(tensor([0., 4., 8.]),
 tensor([[ 0.,  2.],
         [ 4.,  6.],
         [ 8., 10.]]))

## 2.1.5. Saving Memory

In [31]:
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]]))

In [33]:
Y_id = id(Y)
Y = X + Y # point Y to a new memory
Y_id == id(Y)

False

In [34]:
Y_id = id(Y)
Y[:] = X + Y # in-place operation
Y_id == id(Y)

True

In [35]:
Y_id = id(Y)
X += Y # in-place operation
Y_id == id(Y)

True

## 2.1.6. Convert to other python object

In [39]:
# Numpy <==> Tensor
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [42]:
# size-1 tensor <==> scalar
a = torch.tensor([2.6])
a, a.item(), float(a), int(a)

(tensor([2.6000]), 2.5999999046325684, 2.5999999046325684, 2)

# 2.2. Data Preprocessing
> pandas: read_csv, fillna, get_dummies

# 2.3 Linear Algebra

### 2.3.1. Scalars

In [43]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y , x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2. Vectors

In [2]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [3]:
x[3]

tensor(3)

In [6]:
len(x), x.shape

(6, torch.Size([6]))

### 2.3.3. Matrices

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
# Symmetric matrix
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4. Tensor

In [15]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [17]:
# Elementwise operation
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone() # assign a copy of 'A' to 'B'
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [18]:
# Hadamard product
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

### 2.3.5. Reduction

In [20]:
# Summation: Vector
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [22]:
# Summation: Tensor
A, A.shape, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

In [25]:
# Summation by axis
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [27]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [29]:
# Equality expression: sum
A.sum(axis=[0,1]), A.sum()

(tensor(190.), tensor(190.))

In [31]:
# Equality expression: mean
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [35]:
# Non-reduce sum, don't change the dimension
sum_A = A.sum(axis=0, keepdim=True)
sum_A, sum_A.shape

(tensor([[40., 45., 50., 55.]]), torch.Size([1, 4]))

In [38]:
A.shape, A / sum_A  # keepdim can be useful for some matrix calculations

(torch.Size([5, 4]),
 tensor([[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]]))

In [39]:
# Cumulative Sum
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 2.3.6. Dot Products
> Use case: weight sum, x^T * w

In [41]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x,y), torch.sum(x*y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

### 2.3.7. Matrix-Vector Products
> Use case: matrix rotation

In [45]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

### 2.3.8. Matrix-Matrix Multiplication

In [47]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 2.3.9. Norms
> Informally, it tells how big a vector is.

In [48]:
# L1 Norm
u = torch.tensor([3, -4.0])
torch.abs(u).sum()

tensor(7.)

In [49]:
# L2 Norm
torch.norm(u)

tensor(5.)

In [50]:
# Frobenius norm: Like a L2 norm of matrix
torch.norm(torch.ones(4,9))

tensor(6.)