# Numpy - Brief Notes

In [1]:
import numpy as np

array_1D = np.array([1,2,3,4,5])
array_2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
array_3D = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[11,12,13,14,15], [16,17,18,19,20]]])

## 1. Shape

In [2]:
array_1D.shape, array_2D.shape, array_3D.shape

((5,), (2, 5), (2, 2, 5))

In [3]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

## 2. Slicing

In [4]:
array_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
array_2D[0:1] # 第一行

array([[1, 2, 3, 4, 5]])

In [6]:
array_2D[:,0:1] # 第一列

array([[1],
       [6]])

In [7]:
array_2D[array_2D > 6] # 条件判断(T/F)

array([ 7,  8,  9, 10])

## 3. Concatenate

In [10]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

In [11]:
a1, a2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [12]:
np.vstack((a1, a2)), np.concatenate((a1, a2), axis=0) # 纵向合并

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [13]:
np.hstack((a1, a2)), np.concatenate((a1, a2), axis=1) # 横向合并

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))