# Numpy - Brief Notes

In [1]:
import numpy as np

array_1D = np.array([1,2,3,4,5])
array_2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
array_3D = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[11,12,13,14,15], [16,17,18,19,20]]])

## 1. Shape

In [2]:
array_1D.shape, array_2D.shape, array_3D.shape

((5,), (2, 5), (2, 2, 5))

In [3]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

## 2. Slicing

In [4]:
array_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
array_2D[0:1] # 第一行

array([[1, 2, 3, 4, 5]])

In [6]:
array_2D[:,0:1] # 第一列

array([[1],
       [6]])

In [7]:
array_2D[array_2D > 6] # 条件判断(T/F)

array([ 7,  8,  9, 10])

## 3. Concatenate

In [10]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

In [11]:
a1, a2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [12]:
np.vstack((a1, a2)), np.concatenate((a1, a2), axis=0) # 纵向合并

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [13]:
np.hstack((a1, a2)), np.concatenate((a1, a2), axis=1) # 横向合并

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))

## 4. Special Array/Matrix

In [7]:
np.arange(2, 16, 2.5) # 2~16，步长2.5的array,步长可用float

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5])

In [8]:
np.linspace(0, 10, 5) # 0~10的等差数列

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.logspace(0, 3, 4) # 10^0 ~ 10^4 中间的4个等比数列

array([   1.,   10.,  100., 1000.])

In [12]:
np.ones((3,4)) # 3x4全1矩阵

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4)) # 3x4全0矩阵

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.eye(3) # 3x3对角矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.empty((3,4)) #3x4空矩阵，稍微快一些

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 5. Arithmetic

In [4]:
a3 = np.array([[1, 4], [9, 16]])
a3

array([[ 1,  4],
       [ 9, 16]])

In [3]:
np.sqrt(a3) # 开根号

array([[1., 2.],
       [3., 4.]])

In [8]:
a3 ** 2 # n次方

array([[  1,  16],
       [ 81, 256]])

In [7]:
np.exp(a3) # 指数

array([[2.71828183e+00, 5.45981500e+01],
       [8.10308393e+03, 8.88611052e+06]])

In [15]:
a4 = np.array([[1,2,3], [4,5,6]])
a5 = np.array([[1,2],[3,4],[5,6]])
a4, a5

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [27]:
a4.dot(a5), np.dot(a4, a5) # 矩阵点积

(array([[22, 28],
        [49, 64]]),
 array([[22, 28],
        [49, 64]]))

In [26]:
a4 * np.array([1,2,3]) # 单纯元素相乘

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [28]:
a4.T # 转置

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
import numpy.linalg as lg
lg.inv(np.eye(3)) # 单位矩阵的逆矩阵还是本身

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
a5

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a5.max(), a5.min(), a5.mean() # 总体最大，最小，均值

(6, 1, 3.5)

In [34]:
a5.max(axis=0) # 列最大值(行比较)

array([5, 6])

In [35]:
a5.argmax(axis=0) # 列最大值位置

array([2, 2])

In [37]:
a5.mean(axis=0) # 列均值

array([3., 4.])

In [38]:
a5.max(axis=1),  a5.argmax(axis=1), a5.mean(axis=1) # 行最大值(列比较)，位置， 平均

(array([2, 4, 6]), array([1, 1, 1]), array([1.5, 3.5, 5.5]))

In [41]:
a5.var(), a5.std(), a5.sum() # 方差，标准差，求和

(2.9166666666666665, 1.707825127659933, 21)

In [42]:
a5.cumsum() # 累加和

array([ 1,  3,  6, 10, 15, 21])

In [45]:
a5.cumsum(axis=0) # 列累加和(按行运算)

array([[ 1,  2],
       [ 4,  6],
       [ 9, 12]])

In [46]:
a5.cumsum(axis=1) # 行累加和(按列运算)

array([[ 1,  3],
       [ 3,  7],
       [ 5, 11]])